### ISSUE TITLE
ERROR: 0x6 Running GetFileSize on payload.dll

### ISSUE THREAD

**Issue by AdhamAmaad** [deepinstinct/DCOMUploadExec#1]
DCOMUploadExec.exe pc1\johan:pass123@192.168.1.100
[+] create an authenticated IMsiServer on ......
[+] create an authenticated IMsiCustomAction hosted on MSIEXEC.exe -PID 1782
[+] Create a remote GAC file stream 
[-] ERROR: 0x6 Running GetFileSize on payload.dll

**Comment by EliranDI** [comment]
0x6 is ERROR_INVALID_HANDLE - I'm guessing you did not compile the **AssemblyPayload** project
I've added the correct CreateFileW error control so your error will be more informative
[-] ERROR: 0x2 Opening payload.dll - ERROR_FILE_NOT_FOUND

make sure to compile **AssemblyPayload** or provide your own in PayloadConfig.h
